### PR TITLE
fixed receiver

### PR DESCRIPTION
**Pull request by rickjansen-dev**
UART transmitter was not enabled (code was commented out for some reason)

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Tested and confirmed by yourself?

**Comment by rickjansen-dev** [comment]
I do get stuff in now if I run pilight-raw, so yes I assume it's working.
Only thing I changed is the line of code that enables the UART TX Enable bit, which is required to send any data at all

**Comment by CurlyMoo** [comment]
Send from nano to pc i assume?

**Comment by rickjansen-dev** [comment]
Yep, if I open a serial monitor I get the expected stuff like:

c:1311111111321566116133;p:930,380,1970,560,660,1150,6890@c:100100100000000015;p:110,450,720,1840,2380,8020@

c:00000000020030004;p:380,410,2970,1160,8580@

**Pull request merged**
